### ISSUE TITLE
subcommand convert can only handle a few fixed prefixes

### ISSUE THREAD

**Issue by jonassmedegaard** [weso/shapes-rs#92]
Executing `rdfsx convert -m dctap -x uml -f csv -s book.csv -r svg -o book.svg` (from within the examples directory) fails with an error message that the prefix dct is not understood.

Using `rdfsx convert --help`, I fail to see any way to provide the needed prefix.

I would expect an option `--prefix` to allow providing a custom prefix.
I would also expect a few more very common prefixes to be included by default.

**Comment by labra** [comment]
It is possible to inject a custom set of prefix declarations using the `config` option that has been added in version 0.1.5. 

You can use something like:

```sh
rdfsx convert -m dctap -x uml -f csv -s examples/dctap/book.csv -r svg -o target/book.svg --config examples/dctap/book_conv
erter_config.yml
```

and it will use the prefix declarations that appear in the `book_converter_config.yml` file:

```yaml
tap2shex:
  base_iri: "http://example.org/"
  prefixmap:
    dct: "http://purl.org/dc/terms/"
    rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    foaf: "http://xmlns.com/foaf/0.1/"
    xsd: "http://www.w3.org/2001/XMLSchema#"
    sdo: "https://schema.org/"
    ex: "http://example.org/"
```
